=begin
#WizardWorldApi

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'date'
require 'time'

module OpenapiClient
  class FeedbackType
    GENERAL = "General".freeze
    BUG = "Bug".freeze
    DATA_ERROR = "DataError".freeze
    SUGGESTION = "Suggestion".freeze

    def self.all_vars
      @all_vars ||= [GENERAL, BUG, DATA_ERROR, SUGGESTION].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if FeedbackType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #FeedbackType"
    end
  end
end
