=begin
#WizardWorldApi

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'date'
require 'time'

module OpenapiClient
  class SpellType
    NONE = "None".freeze
    CHARM = "Charm".freeze
    CONJURATION = "Conjuration".freeze
    SPELL = "Spell".freeze
    TRANSFIGURATION = "Transfiguration".freeze
    HEALING_SPELL = "HealingSpell".freeze
    DARK_CHARM = "DarkCharm".freeze
    JINX = "Jinx".freeze
    CURSE = "Curse".freeze
    MAGICAL_TRANSPORTATION = "MagicalTransportation".freeze
    HEX = "Hex".freeze
    COUNTER_SPELL = "CounterSpell".freeze
    DARK_ARTS = "DarkArts".freeze
    COUNTER_JINX = "CounterJinx".freeze
    COUNTER_CHARM = "CounterCharm".freeze
    UNTRANSFIGURATION = "Untransfiguration".freeze
    BINDING_MAGICAL_CONTRACT = "BindingMagicalContract".freeze
    VANISHMENT = "Vanishment".freeze

    def self.all_vars
      @all_vars ||= [NONE, CHARM, CONJURATION, SPELL, TRANSFIGURATION, HEALING_SPELL, DARK_CHARM, JINX, CURSE, MAGICAL_TRANSPORTATION, HEX, COUNTER_SPELL, DARK_ARTS, COUNTER_JINX, COUNTER_CHARM, UNTRANSFIGURATION, BINDING_MAGICAL_CONTRACT, VANISHMENT].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if SpellType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #SpellType"
    end
  end
end
