=begin
#WizardWorldApi

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'date'
require 'time'

module OpenapiClient
  class TraitName
    NONE = "None".freeze
    COURAGE = "Courage".freeze
    BRAVERY = "Bravery".freeze
    DETERMINATION = "Determination".freeze
    DARING = "Daring".freeze
    NERVE = "Nerve".freeze
    CHIVALARY = "Chivalary".freeze
    HARDWORKING = "Hardworking".freeze
    PATIENCE = "Patience".freeze
    FAIRNESS = "Fairness".freeze
    JUST = "Just".freeze
    LOYALTY = "Loyalty".freeze
    MODESTY = "Modesty".freeze
    WIT = "Wit".freeze
    LEARNING = "Learning".freeze
    WISDOM = "Wisdom".freeze
    ACCEPTANCE = "Acceptance".freeze
    INTELIGENCE = "Inteligence".freeze
    CREATIVITY = "Creativity".freeze
    RESOURCEFULNESS = "Resourcefulness".freeze
    PRIDE = "Pride".freeze
    CUNNING = "Cunning".freeze
    AMBITION = "Ambition".freeze
    SELFPRESERVATION = "Selfpreservation".freeze

    def self.all_vars
      @all_vars ||= [NONE, COURAGE, BRAVERY, DETERMINATION, DARING, NERVE, CHIVALARY, HARDWORKING, PATIENCE, FAIRNESS, JUST, LOYALTY, MODESTY, WIT, LEARNING, WISDOM, ACCEPTANCE, INTELIGENCE, CREATIVITY, RESOURCEFULNESS, PRIDE, CUNNING, AMBITION, SELFPRESERVATION].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if TraitName.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #TraitName"
    end
  end
end
