=begin
#WizardWorldApi

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::ElixirsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ElixirsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::ElixirsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ElixirsApi' do
    it 'should create an instance of ElixirsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::ElixirsApi)
    end
  end

  # unit tests for elixirs_get
  # @param [Hash] opts the optional parameters
  # @option opts [String] :name 
  # @option opts [ElixirDifficulty] :difficulty 
  # @option opts [String] :ingredient 
  # @option opts [String] :inventor_full_name 
  # @option opts [String] :manufacturer 
  # @return [Array<ElixirDto>]
  describe 'elixirs_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for elixirs_id_get
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [ElixirDto]
  describe 'elixirs_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
