=begin
#WizardWorldApi

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::FeedbackApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FeedbackApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::FeedbackApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FeedbackApi' do
    it 'should create an instance of FeedbackApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::FeedbackApi)
    end
  end

  # unit tests for feedback_post
  # @param [Hash] opts the optional parameters
  # @option opts [SendFeedbackCommand] :send_feedback_command 
  # @return [Object]
  describe 'feedback_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
