=begin
#WizardWorldApi

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::IngredientsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'IngredientsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::IngredientsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IngredientsApi' do
    it 'should create an instance of IngredientsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::IngredientsApi)
    end
  end

  # unit tests for ingredients_get
  # @param [Hash] opts the optional parameters
  # @option opts [String] :name 
  # @return [Array<IngredientDto>]
  describe 'ingredients_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for ingredients_id_get
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [IngredientDto]
  describe 'ingredients_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
