=begin
#WizardWorldApi

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::SpellsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SpellsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::SpellsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SpellsApi' do
    it 'should create an instance of SpellsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::SpellsApi)
    end
  end

  # unit tests for spells_get
  # @param [Hash] opts the optional parameters
  # @option opts [String] :name 
  # @option opts [SpellType] :type 
  # @option opts [String] :incantation 
  # @return [Array<SpellDto>]
  describe 'spells_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for spells_id_get
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [SpellDto]
  describe 'spells_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
