=begin
#WizardWorldApi

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::FeedbackType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::FeedbackType do
  let(:instance) { OpenapiClient::FeedbackType.new }

  describe 'test an instance of FeedbackType' do
    it 'should create an instance of FeedbackType' do
      expect(instance).to be_instance_of(OpenapiClient::FeedbackType)
    end
  end
end
