=begin
#WizardWorldApi

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::SpellType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::SpellType do
  let(:instance) { OpenapiClient::SpellType.new }

  describe 'test an instance of SpellType' do
    it 'should create an instance of SpellType' do
      expect(instance).to be_instance_of(OpenapiClient::SpellType)
    end
  end
end
