=begin
#WizardWorldApi

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/elixir_difficulty'
require 'openapi_client/models/elixir_dto'
require 'openapi_client/models/elixir_inventor_dto'
require 'openapi_client/models/feedback_type'
require 'openapi_client/models/house_dto'
require 'openapi_client/models/house_head_dto'
require 'openapi_client/models/ingredient_dto'
require 'openapi_client/models/send_feedback_command'
require 'openapi_client/models/spell_dto'
require 'openapi_client/models/spell_light'
require 'openapi_client/models/spell_type'
require 'openapi_client/models/trait_dto'
require 'openapi_client/models/trait_name'
require 'openapi_client/models/wizard_dto'
require 'openapi_client/models/wizard_elixir_dto'

# APIs
require 'openapi_client/api/elixirs_api'
require 'openapi_client/api/feedback_api'
require 'openapi_client/api/houses_api'
require 'openapi_client/api/ingredients_api'
require 'openapi_client/api/spells_api'
require 'openapi_client/api/wizards_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
